### ISSUE TITLE
注册界面-年级选择

### ISSUE THREAD

**Issue by TimeSenz** [qcminecraft/qc_classroom#15]
在演示站上，访问注册页面的账号，无法进行年级选择。 表单被隐藏

**Comment by qcminecraft** [comment]
> 在演示站上，访问注册页面的账号，无法进行年级选择。 表单被隐藏

首先感谢提交Issue！
你可能是指提交按钮被disable，因为我这里一切正常
![image](https://user-images.githubusercontent.com/25388328/55078180-7fdd2900-50d4-11e9-87a6-db1463c3e5f6.png)

是这样的，注册账号时首先需要验证手机号，才能取消提交按钮的disable
如果验证手机后问题仍然存在，麻烦提供以下信息：
 - 浏览器版本
 - 截图
 - 从哪里进入的注册页面

以帮助我们继续跟进这个问题，谢谢！

**Comment by TimeSenz** [comment]
你好
我是在deepin系统下的火狐浏览器打开网站，版本为 Firefox 61.0.2 (64 位)
从首页进去后，点击右上角的 未登录用户  -> 注册，进入注册页面

![深度截图_选择区域_20190329181749](https://user-images.githubusercontent.com/20532201/55226469-05391880-5250-11e9-9148-4627017a7a55.png)

发送验证码后填充，年级选择界面未显示。

![深度截图_选择区域_20190329181914](https://user-images.githubusercontent.com/20532201/55226468-05391880-5250-11e9-81f9-98f7849fa696.png)

这个是浏览器开发者工具下看到的代码，我写了一个html的多选框在这个浏览器上打开是可以显示的。在浏览器兼容性上应该是没有什么问题

**Comment by qcminecraft** [comment]
> 你好
> 我是在deepin系统下的火狐浏览器打开网站，版本为 Firefox 61.0.2 (64 位)
> 从首页进去后，点击右上角的 未登录用户 -> 注册，进入注册页面
> 
> ![深度截图_选择区域_20190329181749](https://user-images.githubusercontent.com/20532201/55226469-05391880-5250-11e9-9148-4627017a7a55.png)
> 
> 发送验证码后填充，年级选择界面未显示。
> 
> ![深度截图_选择区域_20190329181914](https://user-images.githubusercontent.com/20532201/55226468-05391880-5250-11e9-81f9-98f7849fa696.png)
> 
> 这个是浏览器开发者工具下看到的代码，我写了一个html的多选框在这个浏览器上打开是可以显示的。在浏览器兼容性上应该是没有什么问题

好的，问题已收到，我会尽力排查，
之前确实遇到过部分浏览器下无法加载选择框的问题，你可以暂时使用Chrome浏览器

（Deepin好评）

**Comment by qcminecraft** [comment]
我刚刚切到了Deepin，使用火狐浏览器(v65.0.1)，无法复现这个BUG，选择框的显示正常...可能是浏览器版本的问题，请问控制台上有报错吗？

**Comment by qcminecraft** [comment]
原因已查明，没有考虑Pjax，已修复！
